replicaCount: 2
image:
  repository: yourrepo/payments-api
  tag: "dev"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: false
  className: nginx
  hosts:
    - host: payments.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
podDisruptionBudget:
  enabled: true
  minAvailable: 1
