apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payments-api
spec:
  ingressClassName: nginx
  rules:
  - host: payments.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payments-api
            port:
              number: 80
